swagger: '2.0'
info:
  title: ms03
  version: 1.0.0
  description: ms03
  x-ibm-name: ms03
paths:
  /claims/{policyId}:
    get:
      operationId: getPolicyId
      responses:
        '200':
          description: The operation was successful.
          schema:
            $ref: '#/definitions/ms03body'
      produces:
        - application/json
      description: Retrieve policyId
      parameters:
        - required: true
          name: policyId
          in: path
          type: string
basePath: /ms03/v1
definitions:
  ms03body:
    type: object
    properties:
      items:
        type: array
        items:
          type: object
          properties:
            claimId:
              type: string
            claimDate:
              type: string
            claimAmount:
              type: integer
x-ibm-configuration:
  type: rest
  phase: realized
  enforced: true
  testable: true
  gateway: datapower-api-gateway
  cors:
    enabled: true
  assembly:
    execute:
      - map:
          version: 2.0.0
          title: map
          inputs:
            policyId:
              schema:
                type: string
              variable: request.parameters.policyId
          outputs:
            response:
              schema:
                $ref: '#/definitions/ms03body'
              variable: message.body
          actions:
            - create: response.items
              actions:
                - set: claimId
                  value: '''claimId'''
                - set: claimDate
                  value: '''YYYY-MM-DDTHH:mm:ss.sssZ'''
                - set: claimAmount
                  value: '100'
    finally: []
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
schemes:
  - https
